### ISSUE TITLE
can't pull from github

### ISSUE THREAD

**Issue by roswitina** [mediaforensics/packages#1]
root@medifor:/opt/pipeline# docker-compose -f docker-compose-full.yml pull
Pulling pgmedifor         ... done
Pulling eqmedifor         ... done
Pulling analytic_workflow ... error
Pulling medifor_ui        ... error
Pulling ac_ela            ... error
Pulling aw_ela            ... error
Pulling ac_exif           ... error
Pulling aw_exif           ... error
Pulling ac_ta2avg         ... error
Pulling aw_ta2avg         ... error

ERROR: for medifor_ui  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/medifor-ui/manifests/latest: no basic auth credentials'

ERROR: for ac_ta2avg  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/ta2avg/manifests/latest: no basic auth credentials'

ERROR: for aw_ela  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials'

ERROR: for ac_ela  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/ela/manifests/latest: no basic auth credentials'

ERROR: for ac_exif  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/exif/manifests/latest: no basic auth credentials'

ERROR: for aw_ta2avg  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials'

ERROR: for aw_exif  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials'

ERROR: for analytic_workflow  b'Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials'
ERROR: Get https://docker.pkg.github.com/v2/mediaforensics/packages/medifor-ui/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/ta2avg/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/ela/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/exif/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials
Get https://docker.pkg.github.com/v2/mediaforensics/packages/analyticworker/manifests/latest: no basic auth credentials
root@medifor:/opt/pipeline#

**Comment by wjdingman1** [comment]
Even though these images are public, I believe you still need to authenticate against the Github package registry by generating a token and logging in through the docker cli.

See here https://medium.com/@sujaypillai/docker-github-package-registry-9e805f16feab

Please let me know if this fixes your issues. Hosting them as packages is more than likely a temporary solution as we will probably being moving to Github Container Registry soon.
